In [1]:
import pandas as pd
import numpy as np
import seaborn as sns 

In [2]:
df = pd.read_csv(r"C:\Users\Jyoti\Downloads\Steel_industry_data.csv")


In [3]:
df.head()

date  Usage_kWh  Lagging_Current_Reactive.Power_kVarh  \
0  01/01/2018 00:15       3.17                                  2.95   
1  01/01/2018 00:30       4.00                                  4.46   
2  01/01/2018 00:45       3.24                                  3.28   
3  01/01/2018 01:00       3.31                                  3.56   
4  01/01/2018 01:15       3.82                                  4.50   

   Leading_Current_Reactive_Power_kVarh  CO2(tCO2)  \
0                                   0.0        0.0   
1                                   0.0        0.0   
2                                   0.0        0.0   
3                                   0.0        0.0   
4                                   0.0        0.0   

   Lagging_Current_Power_Factor  Leading_Current_Power_Factor   NSM  \
0                         73.21                         100.0   900   
1                         66.77                         100.0  1800   
2                         70.28                         100.0  2700   
3                         68.09                         100.0  3600   
4                         64.72                         100.0  4500   

  WeekStatus Day_of_week   Load_Type  
0    Weekday      Monday  Light_Load  
1    Weekday      Monday  Light_Load  
2    Weekday      Monday  Light_Load  
3    Weekday      Monday  Light_Load  
4    Weekday      Monday  Light_Load

In [4]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df.iloc[:,8] = label_encoder.fit_transform(df.iloc[:,8])
df.iloc[:,9] = label_encoder.fit_transform(df.iloc[:,9])
df.iloc[:,10] = label_encoder.fit_transform(df.iloc[:,10])

In [5]:
### split dataset into independent and dependent features
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
x=df.iloc[:,1:]

In [6]:
# X = df.iloc[:,[1,3,5,7,8,9]]
# Y = df.iloc[:,10]

In [7]:
x

Usage_kWh  Lagging_Current_Reactive.Power_kVarh  \
0           3.17                                  2.95   
1           4.00                                  4.46   
2           3.24                                  3.28   
3           3.31                                  3.56   
4           3.82                                  4.50   
...          ...                                   ...   
35035       3.85                                  4.86   
35036       3.74                                  3.74   
35037       3.78                                  3.17   
35038       3.78                                  3.06   
35039       3.67                                  3.02   

       Leading_Current_Reactive_Power_kVarh  CO2(tCO2)  \
0                                      0.00        0.0   
1                                      0.00        0.0   
2                                      0.00        0.0   
3                                      0.00        0.0   
4                                      0.00        0.0   
...                                     ...        ...   
35035                                  0.00        0.0   
35036                                  0.00        0.0   
35037                                  0.07        0.0   
35038                                  0.11        0.0   
35039                                  0.07        0.0   

       Lagging_Current_Power_Factor  Leading_Current_Power_Factor    NSM  \
0                             73.21                        100.00    900   
1                             66.77                        100.00   1800   
2                             70.28                        100.00   2700   
3                             68.09                        100.00   3600   
4                             64.72                        100.00   4500   
...                             ...                           ...    ...   
35035                         62.10                        100.00  82800   
35036                         70.71                        100.00  83700   
35037                         76.62                         99.98  84600   
35038                         77.72                         99.96  85500   
35039                         77.22                         99.98      0   

       WeekStatus  Day_of_week  Load_Type  
0               0            1          0  
1               0            1          0  
2               0            1          0  
3               0            1          0  
4               0            1          0  
...           ...          ...        ...  
35035           0            1          0  
35036           0            1          0  
35037           0            1          0  
35038           0            1          0  
35039           0            1          0  

[35040 rows x 10 columns]

In [8]:
y

0        0
1        0
2        0
3        0
4        0
        ..
35035    0
35036    0
35037    0
35038    0
35039    0
Name: Load_Type, Length: 35040, dtype: int32

In [9]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=4)
model = DecisionTreeClassifier()
model.fit(x_train, y_train)
result = model.score(x_test, y_test)
print(result)

1.0


K Fold Cross Validation

In [10]:
from sklearn.model_selection import KFold
model=DecisionTreeClassifier()
kfold_validation=KFold(10)

In [11]:
import numpy as np
from sklearn.model_selection import cross_val_score
results=cross_val_score(model,x,y,cv=kfold_validation)
print(results)
print(np.mean(results))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
1.0


Stratified K-fold Cross Validation

In [12]:
from sklearn.model_selection import StratifiedKFold
skfold=StratifiedKFold(n_splits=5)
model=DecisionTreeClassifier()
scores=cross_val_score(model,x,y,cv=skfold)
print(np.mean(scores))

1.0


In [13]:
scores

array([1., 1., 1., 1., 1.])

Leave One Out Cross Validation(LOOCV)

In [14]:
from sklearn.model_selection import LeaveOneOut
model=DecisionTreeClassifier()
leave_validation=LeaveOneOut()
results=cross_val_score(model,x,y,cv=leave_validation)

In [15]:
results

array([1., 1., 1., ..., 1., 1., 1.])

In [16]:
print(np.mean(results))

1.0


Repeated Random Test-Train Splits

In [17]:
from sklearn.model_selection import ShuffleSplit
model=DecisionTreeClassifier()
ssplit=ShuffleSplit(n_splits=10,test_size=0.30)
results=cross_val_score(model,x,y,cv=ssplit)

In [18]:

results

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.mean(results)

1.0